configured_endpoints: 4
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-unnatural-group--llc%2Funusualwhales-af5772f8aa2e894b59c3cf99b0f5e5bac24d90a224530bf4de188dcf59f94d79.yml
