configured_endpoints: 14
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-unnatural-group--llc%2Funusualwhales-6a0890d65a5da103cabeabba11c9f31f0b402a86ad334b447d8a455a7513d928.yml
