configured_endpoints: 47
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-unnatural-group--llc%2Funusualwhales-435bf1731c5d007e19fa07041a133f35e9dae59fea506103158087ab0505b89a.yml
